### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by agconti** [agconti/clock#13]
- [ ] Increase clock size for mobile portrait ( #8 ) 
- [ ] Update Tick Animation ( #2 )
- [x]  Normalize data for hour hand ( #14 )
- [x] Clock seconds scale doesn't properly reset to 0 ( #17 )
- [x] Remove black svg flash on load ( #19 )
- [ ] Update text append to use `.data(labels).enter()` ( #16 )
